---

version: '3'

services:
  php-test:
    build: ./docker/php-fpm
    container_name: "php-test"
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    restart: "unless-stopped"
    networks:
      - test-network

  nginx-test:
    image: nginx:1.20
    container_name: "nginx-test"
    restart: "unless-stopped"
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "php-test"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
