settings:
    path: /settings/{service}
    controller: App\Controller\SettingsController::getSettings

settings-set:
    path: /settings-set/{service}
    controller: App\Controller\SettingsController::setSettings